
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export const PdfService = {
  createDoc: (title: string, subtitle?: string, user?: string, branding: string = 'ZARlytics') => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Header Background
    doc.setFillColor(15, 23, 42); // Slate 900
    doc.rect(0, 0, pageWidth, 20, 'F');

    // Header Text
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(branding, 14, 13);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    const dateStr = new Date().toLocaleString();
    doc.text(dateStr, pageWidth - 14, 13, { align: 'right' });

    // Report Title
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 14, 35);

    let currentY = 42;

    if (subtitle) {
      doc.setTextColor(100, 116, 139); // Slate 500
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(subtitle, 14, currentY);
      currentY += 6;
    }

    if (user) {
      doc.setFontSize(9);
      doc.text(`Generated by: ${user}`, 14, currentY);
    }

    return doc;
  },

  generateTable: (doc: jsPDF, headers: string[], data: any[], startY: number = 50) => {
    autoTable(doc, {
      head: [headers],
      body: data,
      startY: startY,
      theme: 'grid',
      headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
      styles: { fontSize: 8, cellPadding: 3, textColor: [30, 41, 59] },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { top: 50 },
      didDrawPage: (data: any) => {
        // Footer on each page
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${data.pageNumber}`, data.settings.margin.left, pageHeight - 10);
      }
    });
  },

  save: (doc: jsPDF, filename: string) => {
    const safeName = filename.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    doc.save(`${safeName}_${new Date().toISOString().slice(0, 10)}.pdf`);
  }
};
